name = "TimeDependentLinearODESystems"
uuid = "d60db074-ae0f-58a7-a558-b5d9c70000d1"
authors = ["HaraldHofstaetter <hofi@harald-hofstaetter.at>"]
version = "0.1.0"

[deps]
Arpack = "7d9fca2a-8960-54d3-9f78-7d1dccf2cb97"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"

[compat]
julia = "≥ 1.0.0"
